version: 2

registries:
  enterprise:
    type: maven-repository
    url: https://timefold.jfrog.io/artifactory/releases/
    # Username is technically a variable, not a secret; but Dependabot quietly ignores variables.
    username: ${{ secrets.JFROG_ENTERPRISE_READ_ONLY_ACCESS_USERNAME }}
    password: ${{ secrets.JFROG_ENTERPRISE_READ_ONLY_ACCESS_TOKEN }}

# Webjars are skipped entirely; we cannot retest the UI of every quickstarts every time a dependency bumps.
multi-ecosystem-groups:
  quickstarts:
    schedule:
      interval: weekly
      time: '03:00' # Otherwise it picks a random time.
    target-branch: "development"
    commit-message:
      prefix: "deps: "
  # Big dependencies (Quarkus, Spring) are treated separately, so that we can decide to merge or not.
  quickstarts-big:
    schedule:
      interval: weekly
      time: '03:00' # Otherwise it picks a random time.
    target-branch: "development"
    commit-message:
      prefix: "deps: "

updates:
  - package-ecosystem: "maven"
    registries:
      - enterprise
    directory: "/"
    patterns: [ "*" ]
    exclude-patterns: [ "*quarkus*", "*spring*", "*webjar*" ]
    multi-ecosystem-group: "quickstarts"
  - package-ecosystem: "gradle"
    registries:
      - enterprise
    directory: "/"
    patterns: [ "*" ]
    exclude-patterns: [ "*quarkus*", "*spring*", "*webjar*" ]
    multi-ecosystem-group: "quickstarts"
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: [ "*" ]
    multi-ecosystem-group: "quickstarts"

  - package-ecosystem: "maven"
    registries:
      - enterprise
    directory: "/"
    patterns: [ "*quarkus*", "*spring*" ]
    multi-ecosystem-group: "quickstarts-big"
  - package-ecosystem: "gradle"
    registries:
      - enterprise
    directory: "/"
    patterns: [ "*quarkus*", "*spring*" ]
    multi-ecosystem-group: "quickstarts-big"
