version: 2

registries:
  maven-artifactory:
    type: maven-repository
    url: https://timefold.jfrog.io/artifactory/releases/
    username: ${{ secrets.JRELEASER_JFROG_USERNAME }}
    password: ${{ secrets.JRELEASER_JFROG_TOKEN }}

multi-ecosystem-groups:
  quickstarts:
    schedule:
      interval: weekly
      time: '03:00' # Otherwise it picks a random time.
    target-branch: "development"
    commit-message:
      prefix: "deps: "

updates:
  - package-ecosystem: "maven"
    registries: "*"
    directory: "/"
    patterns: [ "*" ]
    multi-ecosystem-group: "quickstarts"
  - package-ecosystem: "gradle"
    registries: "*"
    directory: "/"
    patterns: [ "*" ]
    multi-ecosystem-group: "quickstarts"
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: [ "*" ]
    multi-ecosystem-group: "quickstarts"
