version: 2

# Registries are defined in the organization settings.
multi-ecosystem-groups:
  quickstarts:
    schedule:
      interval: weekly
      time: '03:00' # Otherwise it picks a random time.
    target-branch: "development"
    commit-message:
      prefix: "deps: "
  # Big dependencies (Quarkus, Spring) are treated separately, so that we can decide to merge or not.
  quickstarts-quarkus:
    schedule:
      interval: weekly
      time: '03:00' # Otherwise it picks a random time.
    target-branch: "development"
    commit-message:
      prefix: "deps: "
  quickstarts-spring:
    schedule:
      interval: weekly
      time: '03:00' # Otherwise it picks a random time.
    target-branch: "development"
    commit-message:
      prefix: "deps: "

# Webjars are skipped entirely; we cannot retest the UI of every quickstarts every time a dependency bumps.
updates:
  - package-ecosystem: "maven"
    directory: "/"
    patterns: [ "*" ]
    ignore:
      - dependency-name: "org.webjars:*"
      - dependency-name: "io.quarkus:*"
      - dependency-name: "org.springframework:*"
      - dependency-name: "org.springframework.boot:*"
    multi-ecosystem-group: "quickstarts"
  - package-ecosystem: "gradle"
    directory: "/"
    patterns: [ "*" ]
    ignore:
      - dependency-name: "org.webjars:*"
      - dependency-name: "io.quarkus:*"
      - dependency-name: "org.springframework:*"
      - dependency-name: "org.springframework.boot:*"
    multi-ecosystem-group: "quickstarts"
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: [ "*" ]
    multi-ecosystem-group: "quickstarts"

  - package-ecosystem: "maven"
    directory: "/"
    patterns:
      - "io.quarkus:*"
    multi-ecosystem-group: "quickstarts-quarkus"
  - package-ecosystem: "gradle"
    directory: "/"
    patterns:
      - "io.quarkus:*"
    multi-ecosystem-group: "quickstarts-quarkus"

  - package-ecosystem: "maven"
    directory: "/"
    patterns:
      - "org.springframework:*"
      - "org.springframework.boot:*"
    multi-ecosystem-group: "quickstarts-spring"
  - package-ecosystem: "gradle"
    directory: "/"
    patterns:
      - "org.springframework:*"
      - "org.springframework.boot:*"
    multi-ecosystem-group: "quickstarts-spring"
