<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>ai.timefold.solver</groupId>
    <artifactId>timefold-solver-build-parent</artifactId>
    <version>999-SNAPSHOT</version>
    <relativePath/>
  </parent>
  <!-- IMPORTANT: the individual quickstarts have no parent pom. -->

  <artifactId>timefold-solver-quickstarts-parent</artifactId>
  <packaging>pom</packaging>
  <name>Timefold Solver Quickstarts</name>

  <properties>
    <enforcer.failOnDuplicatedClasses>false</enforcer.failOnDuplicatedClasses> <!-- Quarkus. -->
  </properties>

  <modules>
    <module>getting-started/hello-world</module>
    <module>getting-started/spring-boot-integration</module>
    <module>getting-started/service</module>
    <module>quickstarts/school-timetabling</module>
    <module>quickstarts/facility-location</module>
    <module>quickstarts/maintenance-scheduling</module>
    <module>quickstarts/vehicle-routing</module>
    <module>quickstarts/order-picking</module>
    <module>quickstarts/employee-scheduling</module>
    <module>quickstarts/food-packaging</module>
    <module>quickstarts/conference-scheduling</module>
    <module>quickstarts/bed-allocation</module>
    <module>quickstarts/flight-crew-scheduling</module>
    <module>quickstarts/meeting-scheduling</module>
    <module>quickstarts/sports-league-scheduling</module>
    <module>quickstarts/task-assigning</module>
    <module>quickstarts/project-job-scheduling</module>
    <module>quickstarts/tournament-scheduling</module>
    <module>quickstarts/school-timetabling-kotlin</module>
  </modules>

</project>
