<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>ai.timefold.solver</groupId>
    <artifactId>timefold-solver-build-parent</artifactId>
    <version>2.5.0</version>
    <relativePath/>
  </parent>
  <!-- IMPORTANT: the individual quickstarts have no parent pom. -->

  <artifactId>timefold-solver-quickstarts-parent</artifactId>
  <packaging>pom</packaging>
  <name>Timefold Solver Quickstarts</name>

  <properties>
    <enforcer.failOnDuplicatedClasses>false</enforcer.failOnDuplicatedClasses> <!-- Quarkus. -->
  </properties>

  <modules>
    <module>getting-started/hello-world</module>
    <module>getting-started/spring-boot-integration</module>
    <module>getting-started/service</module>
    <module>getting-started/quarkus-integration-kotlin</module>

    <module>use-cases/school-timetabling</module>
    <module>use-cases/facility-location</module>
    <module>use-cases/maintenance-scheduling</module>
    <module>use-cases/vehicle-routing</module>
    <module>use-cases/order-picking</module>
    <module>use-cases/employee-scheduling</module>
    <module>use-cases/food-packaging</module>
    <module>use-cases/conference-scheduling</module>
    <module>use-cases/bed-allocation</module>
    <module>use-cases/flight-crew-scheduling</module>
    <module>use-cases/meeting-scheduling</module>
    <module>use-cases/sports-league-scheduling</module>
    <module>use-cases/task-assigning</module>
    <module>use-cases/project-job-scheduling</module>
    <module>use-cases/tournament-scheduling</module>
  </modules>

</project>
