########################
# Timefold Solver properties
########################

# The solver runs for 30 seconds. To run for 5 minutes use "PT5M" and for 2 hours use "PT2H".
timefold.model.termination.spent-limit=PT30S

# Temporary comment this out to detect bugs in your code (lowers performance)
# quarkus.timefold.solver.environment-mode=FULL_ASSERT

# Temporary comment this out to return a feasible solution as soon as possible
# quarkus.timefold.solver.termination.best-score-limit=0hard/0medium/*soft

# To see what Timefold is doing, turn on DEBUG or TRACE logging.
quarkus.log.category."ai.timefold.solver".level=INFO
# For TRACE logging also activate this:
# quarkus.log.min-level=TRACE
%test.quarkus.log.category."ai.timefold.solver".level=INFO
%prod.quarkus.log.category."ai.timefold.solver".level=INFO

########################
# Model information
########################

timefold.model.id=tournament-scheduling
quarkus.application.name=${timefold.model.id}
timefold.model.name=Tournament Scheduling
model.api.version=v1
timefold.model.api-version=${model.api.version}

timefold.model.contact.email=example@acme.com
timefold.model.contact.name=A.C.M.E.
timefold.model.contact.url=https://acme.com
timefold.model.maturity-level=Example

timefold.model.features[0]=Never assign a team to two matches on the same day.
timefold.model.features[1]=Respect every team's unavailable days.
timefold.model.features[2]=Fairly distribute the number of matches across all teams.
timefold.model.features[3]=Balance how often each pair of teams faces each other.

########################
# Model settings
########################

timefold.model.max-thread-count=16
timefold.model.default-config.max-thread-count=1

########################
# Native build properties
########################

# Enable Swagger UI also in the native mode
quarkus.swagger-ui.always-include=true

########################
# Test overrides
########################

# Effectively disable spent-time termination in favor of the best-score-limit
%test.timefold.model.termination.spent-limit=PT1H
%test.quarkus.timefold.solver.termination.best-score-limit=0hard/0medium/*soft
