########################
# Timefold Solver properties
########################

# The solver runs for 30 seconds. To run for 5 minutes use "PT5M" and for 2 hours use "PT2H".
ai.timefold.orbit.termination.spent-limit=PT30S

# Temporary comment this out to detect bugs in your code (lowers performance)
# quarkus.timefold.solver.environment-mode=FULL_ASSERT

# Temporary comment this out to return a feasible solution as soon as possible
# quarkus.timefold.solver.termination.best-score-limit=0hard/0medium/*soft

# To see what Timefold is doing, turn on DEBUG or TRACE logging.
quarkus.log.category."ai.timefold.solver".level=INFO
# For TRACE logging also activate this:
# quarkus.log.min-level=TRACE
%test.quarkus.log.category."ai.timefold.solver".level=INFO
%prod.quarkus.log.category."ai.timefold.solver".level=INFO

########################
# Model information
########################

timefold.application.id=meeting-scheduling
timefold.application.name=Meeting Scheduling
timefold.application.version=v1
timefold.model.maturity-level=Example
timefold.application.contact.email=info@example.com
timefold.application.contact.name=Your Name
timefold.application.contact.url=https://example.com

########################
# Model settings
########################

ai.timefold.model.max-thread-count=16
ai.timefold.model.default-config.max-thread-count=1

########################
# Native build properties
########################

# Enable Swagger UI also in the native mode
quarkus.swagger-ui.always-include=true

########################
# Test overrides
########################

# Effectively disable spent-time termination in favor of the best-score-limit
%test.ai.timefold.orbit.termination.spent-limit=PT1H
%test.quarkus.timefold.solver.termination.best-score-limit=0hard/0medium/*soft
